import fs from "node:fs/promises";
import path from "node:path";
import type { StorageProvider } from "./types";

const STORAGE_ROOT = path.join(process.cwd(), ".storage", "attachments");

/**
 * Local-disk StorageProvider — the dev/default implementation. Keys are
 * flat filenames (already tenant-namespaced by the caller, e.g.
 * "<tenantId>/<cuid>"), written under .storage/attachments/. A real
 * deployment swaps this for an Azure Blob provider behind the same
 * interface — no caller changes, same pattern as CalendarProvider.
 */
export class LocalStorageProvider implements StorageProvider {
  readonly name = "local";

  private resolvePath(key: string): string {
    // Reject any key that could escape STORAGE_ROOT via path traversal —
    // keys are generated by our own code (tenantId + cuid), never raw user
    // input, but this is cheap insurance against a future caller mistake.
    const resolved = path.join(STORAGE_ROOT, key);
    if (!resolved.startsWith(STORAGE_ROOT)) {
      throw new Error("Invalid storage key");
    }
    return resolved;
  }

  async save({ key, data }: { key: string; data: Buffer }): Promise<void> {
    const filePath = this.resolvePath(key);
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, data);
  }

  async read(key: string): Promise<Buffer | null> {
    try {
      return await fs.readFile(this.resolvePath(key));
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    await fs.rm(this.resolvePath(key), { force: true });
  }
}
